addReviewers: true

addAssignees: author

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - KamalDGRT
  - javeed3157
  - JAYAROSHINI2112

skipKeywords:
  - wip
  - draft
