name: 'Add Project Lead as Reviewer'

on:
  pull_request:

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: AveryCameronUofR/add-reviewer-gh-action@1.0.3
        with: 
          reviewers: "KamalDGRT"
          token: ${{ secrets.GITHUB_TOKEN }}
